steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y python3 python3-pip
        pip3 install --no-cache-dir -r requirements.txt
        uvicorn main:app --host 0.0.0.0 --port $PORT

timeout: '1200s'

images:
  - gcr.io/$PROJECT_ID/my-fastapi-app

deployments:
  - name: 'Deploy to Cloud Run'
    step: 'Deploy to Cloud Run'
    type: 'cloud-run'
    service: 'my-fastapi-app'
    region: 'us-central1'
    source: '.'
    entrypoint: 'uvicorn'
    args: ['main:app', '--host', '0.0.0.0', '--port', '$PORT']
